### ISSUE TITLE
Add microsite to a new static site generators category?

### ISSUE THREAD

**Issue by Siilwyn** [talentlessguy/awesome-node-esm#1]
What would you think of adding [microsite](https://github.com/natemoo-re/microsite/), possibly under a new category for static site generators? It's completely ESM, and thinks it fits perfectly in this list.

**Comment by v1rtl** [comment]
For a new category there should be at least 1 more items

**Comment by Siilwyn** [comment]
Ah that's a bummer but understandable. What do you think of putting it under the 'SSR' category or 'Other'?

Otherwise I'll close this issue until I found another awesome project that fits in this category.

**Comment by v1rtl** [comment]
You could send a PR with the link
